### PR TITLE
fixed python3 bug in ChefAPI.from_config_file

### PR DESCRIPTION
**Pull request by dustinbrown**

### CODE REVIEW

**Comment by coderanger** [comment]
Which version of Python 3? Because the tests are currently passing on 3.4 and 3.5, though I don't remember if this code has a good test or not :)

**Comment by dustinbrown** [comment]
Using 3.5.1.  My knife.rb configuration file using interpolated values and that code path wasn't tested.  I added a new test to cover it.  Thoughts?

**Comment by dustinbrown** [comment]
Bump @coderanger

**Comment by dustinbrown** [comment]
Bump @coderanger Is there anything I can do to help with this?

**Comment by coderanger** [comment]
Sorry for the delay, looks good.

**Comment by coderanger** [comment]
(for anyone that finds this later, this might break 2.6 compat if I hadn't already done that. I do not consider that a bug)

**Pull request merged**
